# fly.toml app configuration file generated for instabotv3 on 2023-10-24T20:53:00+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "instabotv3"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
